--테이블명 DEPT2
--DEPT_NO 숫자타입 3글자
--DEPT_NAME 가변형문자 15바이트
--LOCA_NUMBER 숫자타입 4글자
--DEPT_GENDER 고정문자 1글자
--REG_DATE 날짜타입
--DEPT_BONUS 실수 5자리까지

CREATE TABLE DEPT2 (
    DEPT_NO NUMBER(3),
    DEPT_NAME VARCHAR2(15),
    LOCA_NUMBER NUMBER(4),
    DEPT_GENDER CHAR(1),
    REG_DATE DATE,
    DEPT_BONUS NUMBER(10, 5)
);

--테이블 1행 삽입
INSERT INTO DEPT2 VALUES(123, 'HELLO', 8425, 'V', SYSDATE, 426.84562);

SELECT * FROM DEPT2;

